### PR TITLE
Get classification store attributes

### PR DESCRIPTION
**Pull request by manmohan-pimcore**
Added code on DefaultValue in the output channel bundle that could use some sort of classification store getter to extract a value if it is prefixed with #cs#

### CODE REVIEW

**Comment by daves-weblab** [comment]
Hi @manmohan-pimcore I think you forgot some imports in the `DefaultValue` for accessing the `Classificationstore\GroupConfig`. I think you need a `use Pimcore\Model\DataObject\Classificationstore;` for it to work.

Also could you please update the docs on how to use this feature? Thanks!

**Comment by manmohan-pimcore** [comment]
Hi, @daves-weblab I have commit changes for use Pimcore\Model\DataObject\Classificationstore;

Thanks!

**Comment by dvesh3** [comment]
@manmohan-pimcore could you please sign the CLA? https://github.com/pimcore/output-data-config-toolkit/pull/29#issuecomment-823291307 thanks!

**Comment by dvesh3** [comment]
@manmohan-pimcore thanks a lot!

**Pull request merged**
